### ISSUE TITLE
LRP for multitask regression learning

### ISSUE THREAD

**Issue by vedhas** [sebastian-lapuschkin/lrp_toolbox#15]
# Summarised Question:
### What I attempted so far:
As per [your advise](https://github.com/sebastian-lapuschkin/lrp_toolbox/issues/12) here, I now train my regression model in keras  --> I copy over the weights and model topology (#layers, #nodes, activations), and rebuild it with lrp toolbox modules to use your LRP/DTD computation. 

Now, if I want to run multitask learning, = say I have 3 output predictions (regression on all the three outputs), how do I compute relevance of the input features for predicting a certain output, say output1?

For the simple single output case, I have been doing the following:
```
ypred = nn.forward(xs)       #xs is 2 dimensional = [#samples, #features]
Rsum = nn.lrp(ypred,'epsilon',1.).sum(axis=0)  
 #Summing the relevance scores across samples, Rsum=[1,#features ]
```
For the 3 outputs case [op0,op1,op2], to compute relevance of input features in predicting op1, do I do this??:
```
ypred = nn.forward(xs)[:,1]       #NOTE [:,1] !!! Rest same.
Rsum = nn.lrp(ypred,'epsilon',1.).sum(axis=0)  
 #Summing the relevance scores across samples, Rsum=[1,#features ]
```
I then get this error:
```
Traceback (most recent call last):
  File "/home/panditve/workspace/CurWorkDir/LrpExplainScikitMultiTask.py", line 833, in <module>
    Rsum[0,:] = nn.lrp(ypred).sum(axis=0)
  File "/home/panditve/workspace/CurWorkDir/modules/sequential.py", line 316, in lrp
    R = m.lrp(R,lrp_var,param)
  File "/home/panditve/workspace/CurWorkDir/modules/module.py", line 112, in lrp
    return self._simple_lrp(R)
  File "/home/panditve/workspace/CurWorkDir/modules/linear.py", line 129, in _simple_lrp
    return ((Z / Zs) * R[:,na,:]).sum(axis=2)
IndexError: too many indices for array
```
In attempt to rootcause, I printed array shapes before the error line, got me this:
```
print(Z.shape)     #Works
print(Zs.shape)   #Works
print(R.shape)    #Works
print(R[:,na,:].shape) # ERROR!
print(((Z / Zs) * R[:,na,:]).shape)
return ((Z / Zs) * R[:,na,:]).sum(axis=2)

(14033, 16, 3)  #Z.shape
(14033, 1, 3)    #Zs.shape
(14033,)           #R.shape
Traceback (most recent call last):
  File "/home/panditve/workspace/CurWorkDir/LrpExplainScikitMultiTask.py", line 833, in <module>
    Rsum[0,:] = nn.lrp(ypred).sum(axis=0)
  File "/home/panditve/workspace/CurWorkDir/modules/sequential.py", line 316, in lrp
    R = m.lrp(R,lrp_var,param)
  File "/home/panditve/workspace/CurWorkDir/modules/module.py", line 112, in lrp
    return self._simple_lrp(R)
  File "/home/panditve/workspace/CurWorkDir/modules/linear.py", line 127, in _simple_lrp
    print(R[:,na,:].shape)
IndexError: too many indices for array
```

**Comment by sebastian-lapuschkin** [comment]
Regarding your first, single sample example: I assume, since you are using a regression model, you want to have an explanation of the composition of your prediction in terms of input component contributions *for each output separately*.

What your first three-line piece of code gets you, however, is a weighted sum over explanations for each output neuron. Blindly applying LRP as is -- that is, also for the final layer -- will backpropagate relevance for ALL output neurons.

You get the error above since you lose an axis  and reduce the dimensionality of your output features (R, in your posted stack trace).
Your thought, however, goes in the right direction, but 
`R.shape` (the one you receive as input) should be the same as `Y.shape`.


Here, you should select the output class you are interested in by masking the others, e.g.
```
ypred = forward(xs) 
#create a binary mask for input relevance selection
mask = np.zeros_like(ypred)
mask[ : , np.argmax(ypred, axis=2)] = 1
R = nn.lrp(ypred * mask , ... )
```

in above example, `mask` is used to weight the entries of the larges ypred for each sample with 1 and the rest with 0. This means that setting up `Rinit = ypred * mask` like that results in an analysis of the prediction for the dominant output. Instead of `argmax`, you could choose an arbitrary output index and thus explain each model prediction wrt to all possible outputs `i`.

```
ypred = forward(xs) #forward propagate once to populate hidden activations
#now, analyze the predictions for xs wrt all classes
R_all_outputs = [ ]
for i in range(ypred.shape[1]):
    mask = np.zeros_like(ypred)
    mask[ : , i] = 1
    R_all_outputs.append(nn.lrp(ypred * mask , ... ))
```

above examples should work for batch sizes > 1.
