### ISSUE TITLE
Load error in online demo

### ISSUE THREAD

**Issue by maelh** [sebastian-lapuschkin/lrp_toolbox#20]
Hi,

When you load the following page in Firefox you get the error:

>  Bollocks, something went wrong!

http://heatmapping.org/mnist.html

After clicking on "Handwriting Classification" the proper page loads.

If going to the website https://lrpserver.hhi.fraunhofer.de/handwriting-classification directly (opening in a new window), it will show less options than if embedded in heatmapping.org, for some reason. It will just have a classify button, whereas the embedded version has the options:
- Relevance Propagation Formula
- Beta
- Model
- Hatmap Color Map

**Comment by sebastian-lapuschkin** [comment]
Hi @maelh, 

thank you for pointing that out.
The web demo is using the lrp demo as its backend. However, the front end is the work of @lecode-official

Let's see what he recommends, beyond fixing the links to the one you suggested (and similar targets).

**Comment by lecode-official** [comment]
Hi @maelh,

thanks for pointing out the problem. These are two separate problems:

The embedding on heatmapping.org actually pre-dates the current LRP Demo website. The URL in the iframe is incorrect and has to be updated. I cannot do that, because I do not manage the heatmapping.org website. Maybe @sebastian-lapuschkin can do that. In that case update the URLs as follows:

MNIST: https://lrpserver.hhi.fraunhofer.de/handwriting-classification
Caffe: https://lrpserver.hhi.fraunhofer.de/image-classification
Text: https://lrpserver.hhi.fraunhofer.de/text-classification

The second problem, that you have more options in the embedded version is likely due to the window size. The demo website is responsive and shows more options the more screen space is available. But the iframe in which the LRP Demo Website is embedded on heatmapping.org actually has a fixed size: width="1120" height="1000", which means that even if you have less screen space, the demo will always be displayed at that size. I guess you have opened the website on a mobile device or on a small screen, therefore, when opening the embedded version you get more options than when you are directly on the LRP Demo Website. Try opening the website on a Laptop or Desktop, then you should be able to see all options.

**Comment by sebastian-lapuschkin** [comment]
I have updated the links to the online demos according to the provided info.
The links on heatmapping.org are fine btw, and point to the correct location.
Please let me know if any other issues persist. Closing for now.
