### ISSUE TITLE
Possibility of loading a .h5 model from keras?

### ISSUE THREAD

**Issue by AlexVaith** [sebastian-lapuschkin/lrp_toolbox#21]
Hi I wanted to try out your toolbox with my custom model generated with keras. Keras saves models as .h5 files. What do I have to do to use your toolbox with my won model. Loading the h5 file doe not work.

**Comment by sebastian-lapuschkin** [comment]
Hi Alex,

the python code of this repo has been written to exemplify how LRP works. So it brings along its own definitions of layers.
For loading a Keras-based model, you would have to translate your model into the layers provided by the toolbox code and then ensure that the model still behaves identically.

Since you already have a keras model, I would suggest you check out [iNNvestigate](https://github.com/albermax/innvestigate), which also implements LRP and provides some recommended presets for using LRP with feed-forward architectures.

**Comment by AlexVaith** [comment]
Thanks for reaching out that fast. iNNvestigate looks really promising and straight forward for keras and tensorflow models. But is it applicable to sensor data or just images? From their github page it looks like evrything is focussed on images. Thats what brought me to your repository, because u applied it to human gait, just like I want to do

**Comment by sebastian-lapuschkin** [comment]
I am not the main developer of iNNvestigate, but from my understanding you should be able to process your data and models anyway. In the past some users have had expericended problems with conv1d-layers, which should however be covered.

iNNvestigate is easy to use "out of the box", but customizing it can become ugly, since everything is expressed in terms of Keras layers.

depending on the kind(s) of model you have, I would first recommend trying an application of iNNvestigate and if that does not work attempt to transfer your model parameters to the numpy/cupy toolbox.

what kind of architectures are we looking at?

**Comment by AlexVaith** [comment]
My model consists of conv1d and lstm layers.

**Comment by sebastian-lapuschkin** [comment]
This repo pre-dates the resurgence of LSTM layers.
My colleage Leila Arras has been working on LRP for LSTM architectures  (for which LRP benefits from custom treatment) .
Maybe her repo and papers will help you.
Please [have a look](https://github.com/ArrasL/LRP_for_LSTM) and [get in touch](http://iphome.hhi.de/arras/)!

**Comment by AlexVaith** [comment]
After checking her repository, I feel like I cannot use it for my model as well, because she only implemented it for lstm and linear layers. If I would use caffe to train my model, could I user your repo with the aforementioned layers? Or is the lstm layer in general constrained except for her repository?

**Comment by sebastian-lapuschkin** [comment]
I am not sure if the caffe code in this repo even supports LSTM layers... It is pretty old and we had to add our functionality into relvant existing layers. It seems to me that you might be better off sticking to Keras then, and adding LSTM-LRP backward rules based on Leila's work (still reach out to her, she can at least advise)

best,
