### ISSUE TITLE
how to get relevance for specific layers in CNN using LRP matlab toolbox

### ISSUE THREAD

**Issue by zjjdcrn** [sebastian-lapuschkin/lrp_toolbox#22]
Hi
I was trying to use the LRP matlab toolbox to get the R for specific layer, but seems that I could only get the R for the first layer. Could anyone give an example code? Thanks very much!
I looked the lrp_cnn_demo.m, did not find a way to get R for other layers...

**Comment by sebastian-lapuschkin** [comment]
Hi @zjjdcrn ,

there are two ways to obtain relevance for intermediate layers right now. Both are simple, yet not out-of-the-box-solutions.


Solution 1: Loop over the modules themselves.
The toolbox comes with a Sequential module, which manages a sequence of NN layers. Sequential.m:366 loops over the modules from the output to the input, propagating the relevance through the input.
Given a network, you could (from the output) explicitly call
```
net = ...
for i = length(net.modules):-1:1
    R = net.modules{i}.lrp(R, lrp_var, param );
end
``` 
instead of calling `net.lrp(...)`

Solution 2: The second alternative is to extend the layer implementations miminally, in order to remember the back-propagated relevances. There are two steps to this. In the constructor of each layer you need, add `obj.R = []` to reserve a variable `R` for storing the relevance. (It should be enough to only do this in `+modules/Module.m:21`, as all other layers inherit from this class. Then, just store the computed `R`  before returning it, e.g. add the line `obj.R = R` in `+modules/Module.m:139`.
Thereafter, you should be able to access the relevance of each (hidden) layer as
```
net.modules{i}.R
```

Note however, that this data can become a lot, depending on your network and batch size. Consider also extending the `clean` functions to get rid of the `obj.R`, or introduce a switch with enables or disables the saving of relevance.

**Comment by zjjdcrn** [comment]
Thanks Sebastian! I got the relevance for each layer using the method you provided! 
However, I could not plot them as the R of the first layer, in a scale of raw image. I am learning this with the MNIST model. Dimension of R for the first layer is 1*32*32, but for other layers, it is a 4D matrix, since there are multiple channels/neurons. How could I match each neuron's R back to the raw image?
Appreciate your quick response and help!

**Comment by sebastian-lapuschkin** [comment]
There is two ways to obtain your desired results (1) is quick and dirty and (2) is the "canonical" way to follow for LRP. Both do only work vor CNN type models, ie within the stack of convolutions and pooling layers of the model (due to their local scope), and not for dense layers (To be specific, the solution will *technically* work, but the obtained results will tell you nothing of value).

1) Quick and Dirty: Take your 4D tensor of hidden layer Relevances, sum over the Channel axis (axis-specific information will be lost) to obtain a 3D tensor, then interpolate the spatial axes of the 3D tensor to match the input shape.

2) The "proper" way: For this, you can use the method `+modules/Module.set_lrp_parameters` to specify per layer, which LRP variant and parameter to use. Given a layer `l` for which you have obtained the 4D relevance tensor, and then relate that relevance to the input space. You could use the basic `z`-rule for all layers above and including `l` to perform "normal" LRP, and below `l` use the `flat` rule, which evenly distributes a neuron's relevance across its receptive field. This allows you to link your hidden layer relevance to the input domain [(see this for reference)](https://arxiv.org/abs/1910.09840). In Code:
```
net = ...
l = some_index
for i in length(net.modules)
    if i < l
        net.set_lrp_parameters('flat')
    else
        net.set_lrp_parameters('z')
    end
end

net.lrp(R)
```
Caution on calling `net.lrp()` though. Explicitly giving LRP parameters in the LRP call will override the previously set parameters per layer.

**Comment by zjjdcrn** [comment]
Thanks again Sebastian! 
I could not implement the second method since there the 'z' isn't included in the matlab set_lrp_parameters. I have a big concern for the first method, the fully connected layer I used is 1*1*256, if I sum across the channels, then it will be impossible to interpolate back to the input shape. Will the channel information lost in the second method?

**Comment by sebastian-lapuschkin** [comment]
Apologies, there is no `z` in *this* toolbox. You can use `'none'` or `'simple'`, which select the z-Rule.

Regarding the first method, I was assuming convolution layers. If you have to bridge fully connected layers, however, the 2nd option will not help you as well. the `flat` rule evenly distributes the relevance of a neuron to all its inputs. The output neuron of a dense layer feeds from *all* neurons of the previous layer. You will thus lose all fidelity towards the input in this case.

**Comment by zjjdcrn** [comment]
Got it! Thanks a lot!
